// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Generator.Infrastructure.EntityFrameworkCore;

namespace Generator.Infrastructure.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Generator.Infrastructure.EntityFrameworkCore.Customers.Records.CustomerRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Generator.Infrastructure.EntityFrameworkCore.Orders.Records.OrderDetailRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId");

                    b.Property<int>("ProductId");

                    b.Property<decimal>("Quantity");

                    b.Property<byte?>("StatusId");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StatusId");

                    b.ToTable("OrderDetailRecord");
                });

            modelBuilder.Entity("Generator.Infrastructure.EntityFrameworkCore.Orders.Records.OrderDetailStatusRecord", b =>
                {
                    b.Property<byte>("Id");

                    b.Property<string>("Code");

                    b.HasKey("Id");

                    b.ToTable("OrderDetailStatusRecord");
                });

            modelBuilder.Entity("Generator.Infrastructure.EntityFrameworkCore.Orders.Records.OrderRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId");

                    b.Property<byte>("StatusId");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StatusId");

                    b.ToTable("OrderRecord");
                });

            modelBuilder.Entity("Generator.Infrastructure.EntityFrameworkCore.Orders.Records.OrderStatusRecord", b =>
                {
                    b.Property<byte>("Id");

                    b.Property<string>("Code");

                    b.HasKey("Id");

                    b.ToTable("OrderStatusRecord");
                });

            modelBuilder.Entity("Generator.Infrastructure.EntityFrameworkCore.Products.Records.ProductRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ListPrice");

                    b.Property<string>("ProductCode");

                    b.Property<string>("ProductName");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Generator.Infrastructure.EntityFrameworkCore.Orders.Records.OrderDetailRecord", b =>
                {
                    b.HasOne("Generator.Infrastructure.EntityFrameworkCore.Orders.Records.OrderRecord", "Order")
                        .WithMany("OrderDetail")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Generator.Infrastructure.EntityFrameworkCore.Products.Records.ProductRecord", "Product")
                        .WithMany("OrderDetail")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Generator.Infrastructure.EntityFrameworkCore.Orders.Records.OrderDetailStatusRecord", "Status")
                        .WithMany("OrderDetail")
                        .HasForeignKey("StatusId");
                });

            modelBuilder.Entity("Generator.Infrastructure.EntityFrameworkCore.Orders.Records.OrderRecord", b =>
                {
                    b.HasOne("Generator.Infrastructure.EntityFrameworkCore.Customers.Records.CustomerRecord", "Customer")
                        .WithMany("Order")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Generator.Infrastructure.EntityFrameworkCore.Orders.Records.OrderStatusRecord", "Status")
                        .WithMany("Order")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
